kind: Service
apiVersion: v1
metadata:
  name: tinydemo
  labels:
    app: tinydemo
    app.kubernetes.io/component: tinydemo
    app.kubernetes.io/instance: tinydemo
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deploymentconfig: tinydemo
status:
  loadBalancer: {}
